"""
FastAPI Model Serving Server
==============================
Production-ready REST API for medical AI model inference with input validation,
prediction logging, health checks, model version routing, and compliance headers.

Design principles:
  - All predictions logged with timestamp, model version, and input hash (audit trail)
  - Input validated against schema before inference
  - Confidence thresholds configurable per deployment context
  - Health endpoint reports model readiness, not just server liveness
  - Structured JSON logs for downstream monitoring

FDA/Regulatory Alignment:
  - Audit trail supports post-market surveillance (21 CFR 820.198)
  - Model version tracking enables PCCP change management
  - Input validation prevents inference on out-of-distribution data

Usage::

    uvicorn src.deployment.model_server:app --host 0.0.0.0 --port 8000

    # Or with model path override:
    MODEL_PATH=models/v2 uvicorn src.deployment.model_server:app --port 8000
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import uvicorn
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

# Optional MLflow integration
try:
    import mlflow.pyfunc
    MLFLOW_AVAILABLE = True
except ImportError:
    MLFLOW_AVAILABLE = False

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

MODEL_PATH = os.environ.get("MODEL_PATH", "models/current")
MODEL_NAME = os.environ.get("MODEL_NAME", "medml_classifier")
MODEL_VERSION = os.environ.get("MODEL_VERSION", "latest")
MODEL_REGISTRY_PATH = os.environ.get("MODEL_REGISTRY_PATH", "mlruns/")
CONFIDENCE_THRESHOLD = float(os.environ.get("CONFIDENCE_THRESHOLD", "0.5"))
LOG_PREDICTIONS = os.environ.get("LOG_PREDICTIONS", "true").lower() == "true"
PREDICTION_LOG_PATH = os.environ.get("PREDICTION_LOG_PATH", "logs/predictions.jsonl")
MAX_BATCH_SIZE = int(os.environ.get("MAX_BATCH_SIZE", "100"))

# ---------------------------------------------------------------------------
# Pydantic Schemas
# ---------------------------------------------------------------------------

class PredictionRequest(BaseModel):
    """Single prediction request with input features."""
    features: dict[str, float | int | str] = Field(
        ...,
        description="Feature key-value pairs. All required features must be present.",
        example={"age": 55, "feature_1": 0.82, "feature_2": -0.14},
    )
    patient_id: str | None = Field(
        None,
        description="Optional de-identified patient identifier for audit logging.",
    )
    request_id: str | None = Field(
        None,
        description="Client-provided request ID for tracing.",
    )
    confidence_threshold_override: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Override default confidence threshold for this request.",
    )
    model_version: str | None = Field(
        None,
        description="Request a specific model version. Defaults to current.",
    )

    @field_validator("features")
    @classmethod
    def features_not_empty(cls, v: dict) -> dict:
        if not v:
            raise ValueError("features dict cannot be empty")
        return v


class BatchPredictionRequest(BaseModel):
    """Batch prediction request."""
    requests: list[PredictionRequest] = Field(
        ...,
        description="List of prediction requests.",
        min_length=1,
    )

    @field_validator("requests")
    @classmethod
    def batch_size_check(cls, v: list) -> list:
        if len(v) > MAX_BATCH_SIZE:
            raise ValueError(f"Batch size {len(v)} exceeds maximum {MAX_BATCH_SIZE}")
        return v


class PredictionResponse(BaseModel):
    """Prediction response with probability, binary decision, and metadata."""
    request_id: str
    prediction_id: str
    model_name: str
    model_version: str
    probability: float = Field(..., ge=0.0, le=1.0,
                               description="Predicted probability for positive class.")
    predicted_class: int = Field(..., description="Binary prediction (0 or 1).")
    confidence_threshold: float
    high_confidence: bool = Field(
        ...,
        description="True if probability is above (1 - threshold) or below threshold "
                    "i.e., unambiguous prediction.",
    )
    processing_time_ms: float
    timestamp: str
    compliance_note: str = (
        "This prediction is generated by an investigational AI system. "
        "Clinical decisions must be reviewed by qualified healthcare professionals."
    )


class HealthResponse(BaseModel):
    """Health check response."""
    status: str          # "healthy" | "degraded" | "unhealthy"
    model_loaded: bool
    model_name: str
    model_version: str
    uptime_seconds: float
    total_predictions_served: int
    last_prediction_at: str | None
    warnings: list[str]


# ---------------------------------------------------------------------------
# Model Registry
# ---------------------------------------------------------------------------

class ModelRegistry:
    """In-process model version registry."""

    def __init__(self):
        self._models: dict[str, Any] = {}
        self._current_version: str = MODEL_VERSION
        self._load_count: dict[str, int] = {}

    def load_model(self, version: str = MODEL_VERSION, path: str | None = None) -> None:
        """Load a model version into registry."""
        model_path = path or MODEL_PATH

        try:
            if MLFLOW_AVAILABLE and not Path(model_path).exists():
                # Try MLflow model URI — retry on transient connection errors
                _mlflow_retries = int(os.environ.get("MLFLOW_CONNECT_RETRIES", "3"))
                for _attempt in range(1, _mlflow_retries + 1):
                    try:
                        model = mlflow.pyfunc.load_model(model_path)
                        logger.info("Loaded MLflow model: %s", model_path)
                        break
                    except Exception as _mlflow_err:
                        if _attempt < _mlflow_retries:
                            logger.warning(
                                "MLflow connection attempt %d/%d failed: %s — retrying",
                                _attempt, _mlflow_retries, _mlflow_err,
                            )
                            import time as _time
                            _time.sleep(2 ** _attempt)
                        else:
                            raise
            else:
                # Fallback: load sklearn/pickle model
                import joblib
                model = joblib.load(model_path)
                logger.info("Loaded joblib model from: %s", model_path)

            self._models[version] = model
            self._load_count[version] = 0
            logger.info("Model version '%s' ready", version)

        except FileNotFoundError:
            logger.warning(
                "Model not found at '%s'. Server will start but predictions unavailable. "
                "Set MODEL_PATH environment variable to model location.",
                model_path,
            )
            self._models[version] = None

    def get_model(self, version: str | None = None) -> Any:
        v = version or self._current_version
        model = self._models.get(v)
        if model is None:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=f"Model version '{v}' not loaded or unavailable.",
            )
        self._load_count[v] = self._load_count.get(v, 0) + 1
        return model

    def set_current_version(self, version: str) -> None:
        if version not in self._models:
            raise ValueError(f"Version '{version}' not loaded")
        self._current_version = version
        logger.info("Current model version set to: %s", version)

    @property
    def current_version(self) -> str:
        return self._current_version

    @property
    def is_loaded(self) -> bool:
        return bool(self._models.get(self._current_version))

    def available_versions(self) -> list[str]:
        return list(self._models.keys())


# ---------------------------------------------------------------------------
# Prediction Logger
# ---------------------------------------------------------------------------

class PredictionAuditLogger:
    """
    JSONL prediction audit logger for post-market surveillance.
    Every prediction is logged with timestamp, model version, input hash,
    and result — without storing raw PHI.
    """

    def __init__(self, log_path: str = PREDICTION_LOG_PATH):
        self.log_path = Path(log_path)
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        self._buffer: list[dict] = []

    def log(
        self,
        prediction_id: str,
        model_version: str,
        input_hash: str,
        probability: float,
        predicted_class: int,
        processing_time_ms: float,
        patient_id_hash: str | None = None,
        request_id: str | None = None,
    ) -> None:
        entry = {
            "prediction_id": prediction_id,
            "timestamp": datetime.utcnow().isoformat(),
            "model_name": MODEL_NAME,
            "model_version": model_version,
            "input_feature_hash": input_hash,    # hash only — no raw features stored
            "patient_id_hash": patient_id_hash,  # hash only — no raw ID stored
            "request_id": request_id,
            "probability": round(probability, 6),
            "predicted_class": predicted_class,
            "processing_time_ms": round(processing_time_ms, 2),
        }

        if LOG_PREDICTIONS:
            with open(self.log_path, "a") as f:
                f.write(json.dumps(entry) + "\n")

        self._buffer.append(entry)

        # Keep buffer bounded
        if len(self._buffer) > 10000:
            self._buffer = self._buffer[-5000:]


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

# Global instances
registry = ModelRegistry()
audit_logger = PredictionAuditLogger()
_start_time = time.time()
_prediction_count = 0
_last_prediction_at: str | None = None

app = FastAPI(
    title="MedML-Ops Inference Server",
    description=(
        "FDA-compliant medical AI inference server with prediction audit logging, "
        "input validation, model version routing, and health monitoring. "
        "Part of the MedML-Ops pipeline."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=[
        {"name": "inference", "description": "Model prediction endpoints"},
        {"name": "health", "description": "Server and model health checks"},
        {"name": "admin", "description": "Model management (restricted)"},
    ],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict in production
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Startup / Shutdown
# ---------------------------------------------------------------------------

@app.on_event("startup")
async def startup_event():
    logger.info("MedML-Ops server starting up...")
    registry.load_model(version=MODEL_VERSION)
    logger.info("Server ready. Model version: %s", registry.current_version)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _hash_features(features: dict) -> str:
    """SHA-256 hash of input features for audit trail (no raw PHI)."""
    content = json.dumps(features, sort_keys=True).encode()
    return hashlib.sha256(content).hexdigest()[:16]


def _hash_patient_id(patient_id: str | None) -> str | None:
    if not patient_id:
        return None
    return hashlib.sha256(patient_id.encode()).hexdigest()[:16]


def _features_to_array(features: dict[str, float | int | str]) -> np.ndarray:
    """Convert features dict to numpy array, skipping non-numeric."""
    numeric = {k: float(v) for k, v in features.items()
               if isinstance(v, (int, float))}
    return np.array(list(numeric.values()), dtype=np.float32).reshape(1, -1)


# ---------------------------------------------------------------------------
# Inference Endpoints
# ---------------------------------------------------------------------------

@app.post(
    "/predict",
    response_model=PredictionResponse,
    tags=["inference"],
    summary="Single prediction",
    description=(
        "Run inference on a single input. Input features are validated, "
        "prediction is logged for audit, and result includes probability and binary decision. "
        "**All predictions are logged for post-market surveillance.**"
    ),
)
async def predict(request: PredictionRequest) -> PredictionResponse:
    global _prediction_count, _last_prediction_at
    start = time.time()
    prediction_id = str(uuid.uuid4())
    request_id = request.request_id or str(uuid.uuid4())

    model = registry.get_model(request.model_version)
    threshold = request.confidence_threshold_override or CONFIDENCE_THRESHOLD

    try:
        feature_array = _features_to_array(request.features)
        y_prob = float(model.predict_proba(feature_array)[0, 1])
        y_pred = int(y_prob >= threshold)
    except AttributeError:
        # MLflow pyfunc predict
        import pandas as pd
        df = pd.DataFrame([request.features])
        result = model.predict(df)
        y_prob = float(result[0]) if hasattr(result, "__iter__") else float(result)
        y_pred = int(y_prob >= threshold)
    except Exception as e:
        logger.error("Inference error: %s", e, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Inference failed: {str(e)}",
        )

    processing_time = (time.time() - start) * 1000
    _prediction_count += 1
    _last_prediction_at = datetime.utcnow().isoformat()

    # Audit log
    audit_logger.log(
        prediction_id=prediction_id,
        model_version=registry.current_version,
        input_hash=_hash_features(request.features),
        probability=y_prob,
        predicted_class=y_pred,
        processing_time_ms=processing_time,
        patient_id_hash=_hash_patient_id(request.patient_id),
        request_id=request_id,
    )

    return PredictionResponse(
        request_id=request_id,
        prediction_id=prediction_id,
        model_name=MODEL_NAME,
        model_version=registry.current_version,
        probability=round(y_prob, 6),
        predicted_class=y_pred,
        confidence_threshold=threshold,
        high_confidence=y_prob > (1 - threshold * 0.5) or y_prob < (threshold * 0.5),
        processing_time_ms=round(processing_time, 2),
        timestamp=datetime.utcnow().isoformat(),
    )


@app.post(
    "/predict/batch",
    tags=["inference"],
    summary="Batch prediction",
    description=f"Run inference on multiple inputs in one request. Max batch size: {MAX_BATCH_SIZE}.",
)
async def predict_batch(batch: BatchPredictionRequest) -> list[PredictionResponse]:
    return [await predict(req) for req in batch.requests]


# ---------------------------------------------------------------------------
# Health Endpoints
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["health"],
    summary="Server health check",
)
async def health_check() -> HealthResponse:
    warnings = []
    if not registry.is_loaded:
        warnings.append("Model not loaded — inference unavailable")
    if not MLFLOW_AVAILABLE:
        warnings.append("MLflow unavailable — running without experiment tracking")

    return HealthResponse(
        status="healthy" if registry.is_loaded else "degraded",
        model_loaded=registry.is_loaded,
        model_name=MODEL_NAME,
        model_version=registry.current_version,
        uptime_seconds=round(time.time() - _start_time, 1),
        total_predictions_served=_prediction_count,
        last_prediction_at=_last_prediction_at,
        warnings=warnings,
    )


@app.get(
    "/health/ready",
    tags=["health"],
    summary="Readiness probe (Kubernetes)",
    status_code=200,
)
async def readiness_probe():
    if not registry.is_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model not loaded",
        )
    return {"ready": True}


@app.get(
    "/health/live",
    tags=["health"],
    summary="Liveness probe (Kubernetes)",
    status_code=200,
)
async def liveness_probe():
    return {"alive": True, "timestamp": datetime.utcnow().isoformat()}


# ---------------------------------------------------------------------------
# Admin Endpoints
# ---------------------------------------------------------------------------

@app.get(
    "/models",
    tags=["admin"],
    summary="List available model versions",
)
async def list_models() -> dict:
    return {
        "current_version": registry.current_version,
        "available_versions": registry.available_versions(),
    }


@app.post(
    "/models/{version}/activate",
    tags=["admin"],
    summary="Switch to a different model version",
)
async def activate_model_version(version: str) -> dict:
    try:
        registry.set_current_version(version)
        return {"message": f"Activated model version: {version}"}
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Start the MedML-Ops inference server")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--reload", action="store_true", help="Enable hot reload (dev mode)")
    args = parser.parse_args()

    uvicorn.run(
        "src.deployment.model_server:app",
        host=args.host,
        port=args.port,
        workers=args.workers,
        reload=args.reload,
    )
